import{a as d,i as c,S as p}from"./assets/vendor-f144e563.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function m(t){const s="43995024-c8f5c7e28b3078307d7d8500b",o="https://pixabay.com",n="/api/",e=new URLSearchParams({key:s,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}),r=`${o}${n}?${e}`;try{const a=await d.get(r),{data:u}=a;if(u&&u.hits)return u.hits;throw new Error("No data received from the server")}catch(a){c.error({title:"Error",message:a.message})}}function f({webformatURL:t,largeImageURL:s,tags:o,likes:n,views:e,comments:r,downloads:a}){return`
<li class="gallery-item">
<a class="gallery-link" href="${s}">
<img src="${t}" alt='${o}'class="gallery-image"/>
</a>
<div class="caption-wrapper">
<p><span>Likes: </span>${n}</p>
<p><span>Views: </span>${e}</p>
<p><span>Comments: </span>${r}</p>
<p><span>Downloads: </span>${a}</p>
</div>
</li>`}function h(t){return t.map(f).join("")}const i={formEl:document.querySelector("#searchForm"),inputEl:document.querySelector("#searchInput"),submitBtn:document.querySelector("#submitButton"),searchRes:document.querySelector("#searchResults"),loaderEl:document.querySelector(".loader"),backdropEl:document.querySelector(".loader-backdrop")},y=new p("#searchResults a",{overlay:!0,captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250,captionClass:"caption",close:!0,showCounter:!0,enableKeyboard:!0,docClose:!0,clasName:"gallery-item-modal"});document.addEventListener("DOMContentLoaded",l);function l(){i.loaderEl.classList.add("visually-hidden"),i.backdropEl.classList.add("visually-hidden")}function g(){i.loaderEl.classList.remove("visually-hidden"),i.backdropEl.classList.remove("visually-hidden")}i.formEl.addEventListener("submit",L);async function L(t){if(t.preventDefault(),i.searchRes.innerHTML="",g(),!i.inputEl.value){c.error({title:"Error",message:"Please enter search parameters"}),l();return}const s=t.target.elements.query.value.trim().toLowerCase();try{const o=await m(s);o.length===0&&c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});const n=h(o);i.searchRes.innerHTML=n,y.refresh(),l()}catch(o){c.error({title:"Error",message:o}),l()}t.target.reset()}
//# sourceMappingURL=commonHelpers.js.map
