import{a as g,i as l,S as L}from"./assets/vendor-f144e563.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function d(o){const t="43995024-c8f5c7e28b3078307d7d8500b",s="https://pixabay.com",i="/api/",e=new URLSearchParams({key:t,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:y,per_page:15}),r=`${s}${i}?${e}`;try{const n=await g.get(r),{data:h}=n;return h.hits}catch(n){l.error({title:"Error",message:n.message})}}function b({webformatURL:o,largeImageURL:t,tags:s,likes:i,views:e,comments:r,downloads:n}){return`
<li class="gallery-item">
<a class="gallery-link" href="${t}">
<img src="${o}" alt='${s}'class="gallery-image"/>
</a>
<div class="caption-wrapper">
<p><span>Likes: </span>${i}</p>
<p><span>Views: </span>${e}</p>
<p><span>Comments: </span>${r}</p>
<p><span>Downloads: </span>${n}</p>
</div>
</li>`}function p(o){return o.map(b).join("")}const a={formEl:document.querySelector("#searchForm"),inputEl:document.querySelector("#searchInput"),submitBtn:document.querySelector("#submitButton"),searchRes:document.querySelector("#searchResults"),loaderEl:document.querySelector(".loader"),backdropEl:document.querySelector(".loader-backdrop"),loadMore:document.querySelector(".js-btn-load")},m=new L("#searchResults a",{overlay:!0,captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250,captionClass:"caption",close:!0,showCounter:!0,enableKeyboard:!0,docClose:!0,clasName:"gallery-item-modal"});document.addEventListener("DOMContentLoaded",c);function c(){a.loaderEl.classList.add("visually-hidden"),a.backdropEl.classList.add("visually-hidden")}function E(){a.loaderEl.classList.remove("visually-hidden"),a.backdropEl.classList.remove("visually-hidden")}function f(){a.loadMore.classList.remove("visually-hidden")}let y=1,u;a.formEl.addEventListener("submit",v);async function v(o){if(o.preventDefault(),a.searchRes.innerHTML="",E(),!a.inputEl.value){l.error({title:"Error",message:"Please enter search parameters"}),c();return}u=o.target.elements.query.value.trim().toLowerCase();try{const t=await d(u);t.length===0&&l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});const s=p(t);a.searchRes.innerHTML=s,m.refresh(),c(),f()}catch(t){l.error({title:"Error",message:t}),c()}o.target.reset()}a.loadMore.addEventListener("click",S);async function S(o){y++;const t=await d(u),s=p(t);a.searchRes.insertAdjacentHTML("beforeend",s),m.refresh(),c(),f()}
//# sourceMappingURL=commonHelpers.js.map
